name: Continous Integration - Build

on: [ push, pull_request ]

jobs:
  lerna-build:
    name: Lerna Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-progress
      - name: Boostrap packages
        run: npm run bootstrap
      - name: Build packages
        run: npm run build
      - name: Test packages
        run: npm run jest
      - name: Publish packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
